### PR TITLE
Better ruggeduino checking

### PR DESCRIPTION
**Pull request by PeterJCLaw**

### CODE REVIEW

**Review by kierdavis — APPROVED** [review]
Code changes look fine to me.

I assume these lint errors are expected (for features that aren't implemented in the API or that pylint can't understand):

```
root@pyenv-dummy-dev-75c67b977-nqw6t:~/pyenv-dummy# ./test
Using config file /dev/null
************* Module check-ref
check-ref.py:181: [E1136(unsubscriptable-object), power_things] Value 'R.power.output' is unsubscriptable
check-ref.py:182: [E1133(not-an-iterable), power_things] Non-iterable value R.power.output is used in an iterating context
check-ref.py:231: [E1101(no-member), alt_duino_things] Instance of 'Ruggeduino' has no 'test' member
check-ref.py:238: [E1101(no-member), alt_duino_things] Instance of 'Ruggeduino' has no 'test' member
check-ref.py:240: [E1101(no-member), alt_duino_things] Instance of 'Ruggeduino' has no 'bake_cake' member
check-ref.py:241: [E1101(no-member), alt_duino_things] Instance of 'Ruggeduino' has no 'bake_cake2' member
```

**Comment by PeterJCLaw** [comment]
Yes, those are all things which are currently not supported.
I've separately wondered about having some other deliberate errors to check that it works, though for the moment those sort-of serve that purpose too.

**Comment by PeterJCLaw** [comment]
(I don't appear to have write access to this repo, so I'll leave this for you to merge)

**Comment by kierdavis** [comment]
> (I don't appear to have write access to this repo, so I'll leave this for you to merge)

hnnnng, why is our github permissioning so janky now

**Comment by PeterJCLaw** [comment]
This went live in https://github.com/srobo/srobo-ide/commit/7a5bcfabef6c36185c802b0576cbfff007729db3

**Pull request merged**
